### ISSUE TITLE
Volume not shown in browser 

### ISSUE THREAD

**Issue by PiSignage** [ednl/piradio#1]
Hi the volume don't seem to be showing on browser what do i need to do to get in showing?

**Comment by ednl** [comment]
1. Add user www-data to group audio: "sudo adduser www-data audio"
2. Set permissions in sudoers file by "sudo visudo" and add this line: "www-data ALL=(ALL) NOPASSWD: /usr/bin/at, /usr/bin/amixer" (The amixer part does it, in this case. 'at' is an extra package to snooze the radio after 3h, needs to be installed with apt-get.)

**Comment by PiSignage** [comment]
Thanks so much worked
